apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
    containers:
    - name: c
    image: gcr.io/<project>/job-wq-1 #change me
    env:
    - name: BROKER_URL
        value: amqp://guest:guest@rabbitmq-service:5672
    restartPolicy: always