apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server-ringo
  name: server-ringo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-ringo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: server-ringo
    spec:
       affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: num
                operator: In
                values:
                - "2"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: NAME
          value: Ringo
        image: awheida/server-ringo
        imagePullPolicy: ""
        name: server-ringo
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}